# Generated by Django 6.0.3 on 2026-04-16 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="QueryCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "query_hash",
                    models.CharField(
                        db_index=True,
                        help_text="structured_query 的 SHA256",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("structured_query", models.JSONField(help_text="原始结构化查询条件")),
                ("results", models.JSONField(help_text="MySQL 查询结果列表")),
                ("total", models.IntegerField(default=0, help_text="结果总数")),
                ("hit_count", models.IntegerField(default=0, help_text="命中次数")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "query_cache",
                "indexes": [
                    models.Index(
                        fields=["updated_at"], name="query_cache_updated_b5f16e_idx"
                    )
                ],
            },
        ),
    ]
