# Generated by Django 6.0.3 on 2026-04-29 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("query_cache", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="querycache",
            name="raw_answer",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="intent_sql_executor 返回的原始 answer（matched_data_ids, aggregations 等）",
            ),
        ),
        migrations.AddField(
            model_name="querycache",
            name="sql_info",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="SQL 生成信息（sql, sql_params, sql_rendered, aggregation_sql 等）",
            ),
        ),
    ]
