# Generated by Django 6.0.3 on 2026-04-22 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("query_cache", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(help_text="自动取用户问题前N字做标题", max_length=200)),
                (
                    "query_hash",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="关联 apps.query_cache 的 query_hash（冗余存储，便于缓存被清理后仍能追溯）",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "structured_query",
                    models.JSONField(
                        blank=True, default=dict, help_text="意图解析后的结构化查询条件"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "query_cache_entry",
                    models.ForeignKey(
                        blank=True,
                        help_text="外键关联到 query_cache 表（同在 SQLite 中）",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conversations",
                        to="query_cache.querycache",
                    ),
                ),
            ],
            options={
                "db_table": "chat_conversation",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "用户"), ("assistant", "助手")], max_length=20
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("intent_query", "意图查询"),
                            ("follow_up", "后续问答"),
                            ("search_record", "搜索记录"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField(help_text="消息文本内容")),
                ("meta", models.JSONField(blank=True, default=dict, help_text="扩展字段")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        help_text="所属对话轮次",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chat.conversation",
                    ),
                ),
            ],
            options={
                "db_table": "chat_message",
                "ordering": ["created_at"],
            },
        ),
    ]
