# Generated by Django 6.0.3 on 2026-05-06 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="QueryRound",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seq", models.PositiveIntegerField(help_text="轮次序号，从1开始")),
                (
                    "round_id",
                    models.CharField(
                        db_index=True,
                        help_text="业务标识，如 2-1",
                        max_length=32,
                        unique=True,
                    ),
                ),
                ("user_query", models.TextField(help_text="用户查询文本")),
                (
                    "intent_dict",
                    models.JSONField(blank=True, default=dict, help_text="意图解析结果"),
                ),
                (
                    "result_type",
                    models.CharField(
                        default="table",
                        help_text="结果类型：table（宽表）/ scalar（聚合标量）",
                        max_length=16,
                    ),
                ),
                ("total", models.IntegerField(default=0, help_text="结果总数")),
                (
                    "columns",
                    models.JSONField(blank=True, default=list, help_text="列名列表"),
                ),
                (
                    "sql_json",
                    models.JSONField(blank=True, default=dict, help_text="SQL 生成信息"),
                ),
                (
                    "structured_query",
                    models.JSONField(blank=True, default=dict, help_text="结构化查询条件"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        help_text="所属对话轮次",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="query_rounds",
                        to="chat.conversation",
                    ),
                ),
            ],
            options={
                "db_table": "chat_query_round",
                "ordering": ["seq"],
                "unique_together": {("conversation", "seq")},
            },
        ),
        migrations.CreateModel(
            name="ResultRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_id", models.BigIntegerField(blank=True, null=True)),
                ("title", models.CharField(default="", max_length=255)),
                ("value_id", models.BigIntegerField(blank=True, null=True)),
                ("property_id", models.BigIntegerField(blank=True, null=True)),
                ("property_name", models.CharField(default="", max_length=255)),
                ("bitmap_role", models.CharField(default="", max_length=64)),
                ("value", models.TextField(blank=True, null=True)),
                (
                    "data_producers",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "data_organizations",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("scalar_property_name", models.CharField(default="", max_length=255)),
                ("scalar_property_id", models.BigIntegerField(blank=True, null=True)),
                ("scalar_result", models.TextField(blank=True, null=True)),
                (
                    "round",
                    models.ForeignKey(
                        help_text="所属查询轮次",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rows",
                        to="chat.queryround",
                    ),
                ),
            ],
            options={
                "db_table": "chat_result_row",
                "ordering": ["id"],
            },
        ),
    ]
