# Generated by Django 6.0.3 on 2026-05-11 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_queryround_resultrow"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resultrow",
            name="round",
        ),
        migrations.CreateModel(
            name="CurrentResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "seq",
                    models.PositiveIntegerField(default=1, help_text="产生该结果的问答轮次序号"),
                ),
                ("data_id", models.BigIntegerField(help_text="实体ID")),
                (
                    "title",
                    models.CharField(blank=True, help_text="数据集/样品标题", max_length=255),
                ),
                (
                    "property_name",
                    models.CharField(help_text="属性英文名称（原始名，不加前缀）", max_length=255),
                ),
                (
                    "bitmap_role",
                    models.CharField(
                        blank=True,
                        help_text="属性类别：object / operate / result",
                        max_length=64,
                    ),
                ),
                (
                    "value_text",
                    models.TextField(blank=True, help_text="属性值（字符串存储）", null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        help_text="所属对话轮次",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="current_results",
                        to="chat.conversation",
                    ),
                ),
            ],
            options={
                "db_table": "chat_current_result",
            },
        ),
        migrations.CreateModel(
            name="InitialResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_id",
                    models.BigIntegerField(help_text="实体ID，同一data_id的行属于同一条数据"),
                ),
                (
                    "title",
                    models.CharField(blank=True, help_text="数据集/样品标题", max_length=255),
                ),
                (
                    "property_name",
                    models.CharField(help_text="属性英文名称（原始名，不加前缀）", max_length=255),
                ),
                (
                    "bitmap_role",
                    models.CharField(
                        blank=True,
                        help_text="属性类别：object / operate / result",
                        max_length=64,
                    ),
                ),
                (
                    "value_text",
                    models.TextField(blank=True, help_text="属性值（字符串存储）", null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        help_text="所属对话轮次",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="initial_results",
                        to="chat.conversation",
                    ),
                ),
            ],
            options={
                "db_table": "chat_initial_result",
            },
        ),
        migrations.DeleteModel(
            name="QueryRound",
        ),
        migrations.DeleteModel(
            name="ResultRow",
        ),
        migrations.AddIndex(
            model_name="currentresult",
            index=models.Index(
                fields=["conversation", "data_id"],
                name="chat_curren_convers_3e9ffe_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="initialresult",
            index=models.Index(
                fields=["conversation", "data_id"],
                name="chat_initia_convers_c518b7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="initialresult",
            index=models.Index(
                fields=["conversation", "property_name"],
                name="chat_initia_convers_ec42c1_idx",
            ),
        ),
    ]
